# Generated by Django 3.1.5 on 2021-02-04 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('number', models.CharField(default=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('route', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Friday',
            fields=[
                ('duty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='friday_duties', serialize=False, to='checker.duty')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('finish_time', models.TimeField(blank=True, null=True)),
                ('card', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='MondayThursday',
            fields=[
                ('duty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mon_thu_duties', serialize=False, to='checker.duty')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('finish_time', models.TimeField(blank=True, null=True)),
                ('card', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Saturday',
            fields=[
                ('duty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='saturday_duties', serialize=False, to='checker.duty')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('finish_time', models.TimeField(blank=True, null=True)),
                ('card', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Sunday',
            fields=[
                ('duty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sunday_duties', serialize=False, to='checker.duty')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('finish_time', models.TimeField(blank=True, null=True)),
                ('card', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fri_rota', to='checker.friday')),
                ('monday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mon_rota', to='checker.mondaythursday')),
                ('saturday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sat_rota', to='checker.saturday')),
                ('sunday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sun_rota', to='checker.sunday')),
                ('thursday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thu_rota', to='checker.mondaythursday')),
                ('tuesday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tue_rota', to='checker.mondaythursday')),
                ('wednesday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wed_rota', to='checker.mondaythursday')),
            ],
        ),
    ]
