# Generated by Django 3.1.5 on 2021-01-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_no', models.CharField(max_length=10)),
                ('mon_thu', models.CharField(max_length=16)),
                ('friday', models.CharField(max_length=16)),
                ('saturday', models.CharField(max_length=16)),
                ('sunday', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saturday', models.CharField(max_length=10)),
                ('sunday', models.CharField(max_length=10)),
                ('monday', models.CharField(max_length=10)),
                ('tuesday', models.CharField(max_length=10)),
                ('wednesday', models.CharField(max_length=10)),
                ('thursday', models.CharField(max_length=10)),
                ('friday', models.CharField(max_length=10)),
            ],
        ),
    ]
