# Generated by Django 3.1.5 on 2021-01-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duty',
            name='friday',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='duty',
            name='mon_thu',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='duty',
            name='saturday',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='duty',
            name='sunday',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
