# Generated by Django 3.1.5 on 2021-01-30 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0002_auto_20210128_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duty',
            old_name='duty_no',
            new_name='route',
        ),
        migrations.RemoveField(
            model_name='duty',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='duty',
            name='id',
        ),
        migrations.RemoveField(
            model_name='duty',
            name='mon_thu',
        ),
        migrations.RemoveField(
            model_name='duty',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='duty',
            name='sunday',
        ),
        migrations.AddField(
            model_name='duty',
            name='number',
            field=models.CharField(default=True, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Sunday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(blank=True)),
                ('finish_time', models.TimeField(blank=True)),
                ('card', models.FileField(blank=True, upload_to='')),
                ('duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checker.duty')),
            ],
        ),
        migrations.CreateModel(
            name='Saturday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(blank=True)),
                ('finish_time', models.TimeField(blank=True)),
                ('card', models.FileField(blank=True, upload_to='')),
                ('duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checker.duty')),
            ],
        ),
        migrations.CreateModel(
            name='MondayThursday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(blank=True)),
                ('finish_time', models.TimeField(blank=True)),
                ('card', models.FileField(blank=True, upload_to='')),
                ('duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checker.duty')),
            ],
        ),
        migrations.CreateModel(
            name='Friday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(blank=True)),
                ('finish_time', models.TimeField(blank=True)),
                ('card', models.FileField(blank=True, upload_to='')),
                ('duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checker.duty')),
            ],
        ),
    ]
