# Generated by Django 3.1.5 on 2021-01-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0003_auto_20210130_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friday',
            name='finish_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='friday',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mondaythursday',
            name='finish_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mondaythursday',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
