# Generated by Django 3.1.5 on 2021-01-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0004_auto_20210130_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saturday',
            name='finish_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saturday',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sunday',
            name='finish_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sunday',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
