# Generated by Django 3.1.5 on 2021-03-05 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EarlyWinter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(default=True, max_length=2)),
                ('year_2021', models.DateField(blank=True, null=True)),
                ('year_2022', models.DateField(blank=True, null=True)),
                ('year_2023', models.DateField(blank=True, null=True)),
                ('year_2024', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Summer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(default=True, max_length=2)),
                ('year_2021', models.DateField(blank=True, null=True)),
                ('year_2022', models.DateField(blank=True, null=True)),
                ('year_2023', models.DateField(blank=True, null=True)),
                ('year_2024', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LateWinter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_2021', models.DateField(blank=True, null=True)),
                ('year_2022', models.DateField(blank=True, null=True)),
                ('year_2023', models.DateField(blank=True, null=True)),
                ('year_2024', models.DateField(blank=True, null=True)),
                ('block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='common_block', to='holidays.earlywinter')),
            ],
        ),
        migrations.AddField(
            model_name='earlywinter',
            name='summer',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='summer_block', to='holidays.summer'),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_block', to='holidays.earlywinter')),
            ],
        ),
    ]
