# Generated by Django 3.1.5 on 2021-03-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summer',
            name='id',
        ),
        migrations.AlterField(
            model_name='summer',
            name='block',
            field=models.CharField(default=True, max_length=1, primary_key=True, serialize=False),
        ),
    ]
