# Generated by Django 3.1.5 on 2021-03-05 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0003_auto_20210305_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latewinter',
            name='id',
        ),
        migrations.AlterField(
            model_name='driver',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_block', to='holidays.earlywinter'),
        ),
        migrations.AlterField(
            model_name='latewinter',
            name='block',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='common_block', serialize=False, to='holidays.earlywinter'),
        ),
    ]
