# Generated by Django 3.1.5 on 2021-03-05 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0004_auto_20210305_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earlywinter',
            name='block',
            field=models.CharField(default=True, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='summer',
            name='block',
            field=models.CharField(default=True, max_length=10, primary_key=True, serialize=False),
        ),
    ]
