# Generated by Django 3.1.5 on 2021-03-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0005_auto_20210305_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summer',
            name='block',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
